[package]
edition = "2018"
name = "zeroblog"
version = "0.1.0"
authors = ["Marie Janssen <jamuraa@base0.net>"]
license = "MIT"

[dependencies]
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
markup = "0.12.2"
